language: node_js

node_js:
  - "7"
  - "8"

cache:
  directories:
    - node_modules

install:
  - npm install

scripts:
  - npm run lint
  - npm run test

after_success:
  - npm run coveralls

notifications:
  webhooks: http://travis.moviecast.xyz/webhook